### ISSUE TITLE
粉丝列表搜索之后切换页面再切回来，仍然显示搜索的结果且无法取消

### ISSUE THREAD

**Issue by suntrian** [suntrian/catior#40]
搜索框的内容为空，但是切换回来之后仍然显示的是搜索的结果。再次点击搜索之后显示 所有内容，但是切换页面再切回来还是之前的关键词的结果
空白点击搜索之后 ，可以显示 所有内容。但是切换页面之后， 仍然是只有关键词的结果

@lovemegowin 怎么搞？

**Comment by lovemegowin** [comment]
在componentWillUnmount的时候把数据清了
